### ISSUE TITLE
Where is PyPI

### ISSUE THREAD

**Issue by KPCOFGS** [AdityaNG/kan-gpt#13]
**Describe the bug**

Where is the PyPI website. I checked the internet and still don't see it. The pypi badge appeared in the README file also does not redirect me to the right page

**Comment by AdityaNG** [comment]
Hello, following is the PyPi. I will make sure to add this link somewhere in the read me file.

https://pypi.org/project/kan-gpt/

**Comment by AdityaNG** [comment]
Resolved by #14
