### ISSUE TITLE
I followed the description as it was, but an error comes out. I post collab.

### ISSUE THREAD

**Issue by gyunggyung** [AdityaNG/kan-gpt#19]
![image](https://github.com/AdityaNG/kan-gpt/assets/26733242/abcae520-4ac4-44bc-8749-1e34c43f045f)
https://colab.research.google.com/drive/1EnRst9ojKYfxjieIQMhsuxje2eveN4DA#scrollTo=ItOjsuy5_ILn

I followed the description as it was, but an error comes out. I post collab.

**Comment by gyunggyung** [comment]
result = tokenizer.decode(y[0])

**Comment by AdityaNG** [comment]
Fixed by #20
