### ISSUE TITLE
relax scikit-learn version

### ISSUE THREAD

**Issue by kpeez** [AdityaNG/kan-gpt#21]
I am attempting to use kan-gpt in a project that requries `scikit-learn>=1.2.2`. However, kan-gpt pins an exact version of scikit-learn in the `requirements.txt` file (`scikit_learn==1.1.3`). If possible, could this be relaxed to `scikit-learn>=1.1.13`?

**Comment by AdityaNG** [comment]
Fixed by #23

**Comment by AdityaNG** [comment]
The release `1.1.0` should fix any dependency issues

https://github.com/AdityaNG/kan-gpt/releases/tag/1.1.0
