### ISSUE TITLE
Increase block size

### ISSUE THREAD

**Issue by AjibolaPy** [AdityaNG/kan-gpt#7]
Can the model block size be increased from 1024 to 3000 atleast?

**Comment by AdityaNG** [comment]
Yes, the block size is variable as shown below:

```py
from kan_gpt.model import GPT
from transformers import GPT2Tokenizer

model_config = GPT.get_default_config()
model_config.model_type = "gpt2"
model_config.vocab_size = 50257
model_config.block_size = 1024
model = GPT(model_config)
```

Check out the [`get_default_config`](https://github.com/AdityaNG/kan-gpt/blob/8a544dd5a5458cf5b1163058143b99d50eeedf11/kan_gpt/model.py#L154C5-L170C17) function for details

**Comment by AjibolaPy** [comment]
Thanks for your reply.
Can I increase the block size, without retraining the model?.
I think block size is same as context length(maximum sequence length) if I'm not wrong

**Comment by AdityaNG** [comment]
Interesting question @AjibolaPy , from my understanding it is possible but challenging to increase the block size without retraining your LLM ([reference](https://www.reddit.com/r/LocalLLaMA/comments/18x8g6c/llm_maybe_longlm_selfextend_llm_context_window/)). And yes, block size is the same as context length
