### ISSUE TITLE
Import module error

### ISSUE THREAD

**Issue by AjibolaPy** [AdityaNG/kan-gpt#9]
After installing the kan_gpt using ```pip install kan_gpt``` on colab.
I got this error when I try to import the library and the model. I copied it from the GitHub readme. 

![Screenshot_20240508-120050.png](https://github.com/AdityaNG/kan-gpt/assets/89350081/81935cc9-a075-4bdf-a760-9855bc0265e0)

**Comment by MagnetonBora** [comment]
I have the same issue.

**Comment by AjibolaPy** [comment]
> I have the same issue.

Have you been able to solve it??
I think it's suppose to be ```from kan_gpt.kan_gpt.effificent_kan.model import GPT``` .
Change it to this and try it

**Comment by AdityaNG** [comment]
Hi all, thank you for reporting this! I have made the fix and pushed it on the new `0.4.0` release
